# Generated by Django 4.1.1 on 2022-10-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('time_active', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
