# Generated by Django 4.1.1 on 2022-10-27 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('time_active', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.museum')),
            ],
        ),
    ]
