# Generated by Django 4.1.1 on 2022-10-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='user',
            name='licenses',
            field=models.ManyToManyField(to='main_app.licence'),
        ),
    ]
