# Generated by Django 4.1.1 on 2022-10-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_licence_alter_fish_options_user_licenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='licenses',
            new_name='licences',
        ),
    ]
