# Generated by Django 4.1.1 on 2022-10-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_licenses_user_licences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
